apiVersion: v1
kind: Secret
metadata:
  name: deduplicacao-secrets
  namespace: barramento-biometrico
  labels:
    app: deduplicacao-service
    team: biometria
    codigo: deduplicacao-service

type: Opaque
data:
  OPENSEARCH_PASSWORD: "QWRtaW5AMTIz" # base64 de Admin@123
