apiVersion: v1
kind: Secret
metadata:
  name: sanitizacao-batch-secrets
  namespace: barramento-biometrico
  labels:
    app: sanitizacao-batch
    team: biometria
    codigo: sanitizacao-batch

type: Opaque
data:
  OPENSEARCH_PASSWORD: "QWRtaW5AMTIz" # base64 de Admin@123
