apiVersion: v1
kind: Service
metadata:
  name: sanitizacao-batch-service
  namespace: barramento-biometrico
  labels:
    app: sanitizacao-batch
    team: biometria
    codigo: sanitizacao-batch
spec:
  type: ClusterIP
  selector:
    app: sanitizacao-batch
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
